=== artefactual/archivematica/src/dashboard/src/components/api/par_schemas/preservation-action.json
{
  "$id": "http://www.parcore.org/schema/preservation-action.json/#",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "anyOf": [
    {
      "required": [
        "inputFiles",
        "outputFiles"
      ]
    },
    {
      "required": [
        "inputProperties",
        "outputFiles"
      ]
    },
    {
      "required": [
        "inputFiles",
        "outputProperties"
      ]
    },
    {
      "required": [
        "inputProperties",
        "outputProperties"
      ]
    },
    {
      "required": [
        "inputFiles",
        "rawOutputs"
      ]
    },
    {
      "required": [
        "inputProperties",
        "rawOutputs"
      ]
    }
  ],
  "definitions": {
    "inputFile": {
      "additionalProperties": false,
      "description": "A file input to a preservation action",
      "properties": {
        "description": {
          "type": "string"
        },
        "file": {
          "$ref": "http://www.parcore.org/schema/types.json/#/definitions/parFile"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "file"
      ],
      "title": "Preservation Action Input File",
      "type": "object"
    },
    "inputProperty": {
      "additionalProperties": false,
      "description": "A property input to a preservation action",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "parProperty": {
          "$ref": "http://www.parcore.org/schema/par-property.json/#"
        }
      },
      "required": [
        "name",
        "description",
        "parProperty"
      ],
      "title": "Preservation Action Input Property",
      "type": "object"
    },
    "outputFile": {
      "additionalProperties": false,
      "description": "An output file from a preservation action",
      "properties": {
        "description": {
          "type": "string"
        },
        "file": {
          "$ref": "http://www.parcore.org/schema/types.json/#/definitions/parFile"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "file"
      ],
      "title": "Preservation Action Output File",
      "type": "object"
    },
    "outputProperty": {
      "additionalProperties": false,
      "description": "An output property from a preservation action",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "parProperty": {
          "$ref": "http://www.parcore.org/schema/par-property.json/#"
        }
      },
      "required": [
        "name",
        "description",
        "parProperty"
      ],
      "title": "Preservation Action Output",
      "type": "object"
    },
    "outputRaw": {
      "additionalProperties": false,
      "description": "A raw output from a preservation action",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "value"
      ],
      "title": "Preservation Action Raw Output",
      "type": "object"
    }
  },
  "properties": {
    "constraints": {
      "additionalItems": false,
      "items": {
        "properties": {
          "allowedFormats": {
            "items": {
              "$ref": "http://www.parcore.org/schema/format.json/#"
            },
            "type": "array"
          },
          "allowedPropertiesAllOf": {
            "items": {
              "$ref": "http://www.parcore.org/schema/par-property.json/#"
            },
            "type": "array"
          },
          "allowedPropertiesAnyOf": {
            "items": {
              "$ref": "http://www.parcore.org/schema/par-property.json/#"
            },
            "type": "array"
          },
          "inputItemName": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "minItems": 1,
      "type": "array"
    },
    "description": {
      "type": "string"
    },
    "example": {
      "type": "string"
    },
    "id": {
      "$ref": "http://www.parcore.org/schema/types.json/#/definitions/parIdentifier"
    },
    "inputFiles": {
      "additionalItems": false,
      "items": {
        "$ref": "http://www.parcore.org/schema/preservation-action.json/#/definitions/inputFile"
      },
      "type": "array"
    },
    "inputProperties": {
      "additionalItems": false,
      "items": {
        "$ref": "http://www.parcore.org/schema/preservation-action.json/#/definitions/inputProperty"
      },
      "type": "array"
    },
    "localLastModifiedDate": {
      "format": "date-time",
      "type": "string"
    },
    "outputFiles": {
      "additionalItems": false,
      "items": {
        "$ref": "http://www.parcore.org/schema/preservation-action.json/#/definitions/outputFile"
      },
      "minItems": 1,
      "type": "array"
    },
    "outputProperties": {
      "additionalItems": false,
      "items": {
        "$ref": "http://www.parcore.org/schema/preservation-action.json/#/definitions/outputProperty"
      },
      "minItems": 1,
      "type": "array"
    },
    "rawOutputs": {
      "additionalItems": false,
      "items": {
        "$ref": "http://www.parcore.org/schema/preservation-action.json/#/definitions/outputRaw"
      },
      "minItems": 1,
      "type": "array"
    },
    "tool": {
      "$ref": "http://www.parcore.org/schema/tool.json/#"
    },
    "type": {
      "$ref": "http://www.parcore.org/schema/preservation-action-type.json/#"
    }
  },
  "required": [
    "id",
    "description",
    "type",
    "tool"
  ],
  "title": "Preservation Action",
  "type": "object"
}

=== artefactual/archivematica/src/dashboard/src/components/api/mediainfo3.json
{
  "constraints": [
    {
      "allowedFormats": [
        {
          "id": {
            "guid": "bf5ae53e-ffb4-4c40-a4f2-5b8e7c53e602",
            "name": "x-fmt/384",
            "namespace": "http://www.nationalarchives.gov.uk/"
          },
          "localLastModifiedDate": "2018-06-14T15:00:00.0Z",
          "name": "Quicktime"
        }
      ],
      "inputItemName": "inputfile"
    }
  ],
  "description": "Extraction of properties for Video files using MediaInfo",
  "example": "commandline 'mediainfo --Output=EBUCore inputfile'",
  "id": {
    "guid": "1caa0cde-e345-44ac-8d83-51afaa7427b6",
    "name": "MediaInfo3",
    "namespace": "http://www.parcore.org/preservation-actions"
  },
  "inputFiles": [
    {
      "description": "File that will have metadata extracted from",
      "file": {
        "filepath": ""
      },
      "name": "inputfile"
    }
  ],
  "rawOutputs": [{
      "description": "EBUCore XML output from MediaInfo",
      "name": "EBUCore",
      "value": "XML"
      }],
  "tool": {
    "toolID": "mediainfo",
    "toolName": "mediainfo",
    "toolVersion": "18.03"
  },
  "type": {
    "id": {
      "guid": "ed411b7f-1e0f-4486-b7b7-9a06835c04d9",
      "name": "http://id.loc.gov/vocabulary/preservation/eventType/mee",
      "namespace": "url"
    },
    "label": "metadata extraction"
  }
}
